namespace: itd27m01
name: oci_openvpn
description: Ansible Roles for OpenVPN setup (Oracle Cloud Infrastructure)
version: 0.1.0
readme: README.md
authors:
  - ITD27M01 (https://github.com/itd27m01)
license_file: LICENSE
tags:
  - oci
  - cloud
  - openvpn
dependencies:
  "itd27m01.oci": "*"
repository: https://github.com/itd27m01/ansible-openvpn-collection
homepage: https://github.com/itd27m01/ansible-openvpn-collection
issues: https://github.com/itd27m01/ansible-openvpn-collection
build_ignore:
  - '*.tar.gz'
  - '*.pyc'
  - '.gitignore'
  - '.github'