---
- name: Install unboud package
  yum:
    name:
      - unbound
    state: latest
  when: ansible_pkg_mgr is defined and ansible_pkg_mgr == "yum"

- name: Install unboud package
  dnf:
    name:
      - unbound
    state: latest
  when: ansible_pkg_mgr is defined and ansible_pkg_mgr == "dnf"

- name: Configure unbound
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    validate: /sbin/unbound-checkconf %s
    backup: yes
  notify:
    - Restart unbound service

- name: Ensure unbound service started
  service:
    name: unbound
    state: started
    enabled: yes
