---
- name: Store ta.key secret
  oracle.oci.oci_vault_secret:
    vault_id: "{{ secret_vault_id }}"
    compartment_id: "{{ secret_compartment_id }}"
    key_id: "{{ secret_key_id }}"
    secret_rules: []
    secret_name: "{{ compartment + '.ta.key' }}"
    secret_content:
      content: "{{ ta_key['content'] }}"
      content_type: 'BASE64'
      stage: 'CURRENT'
  delegate_to: localhost

- name: Store ip secret
  oracle.oci.oci_vault_secret:
    vault_id: "{{ secret_vault_id }}"
    compartment_id: "{{ secret_compartment_id }}"
    key_id: "{{ secret_key_id }}"
    secret_rules: []
    secret_name: "{{ compartment + '.ip' }}"
    secret_content:
      content: "{{ ansible_host | string | b64encode }}"
      content_type: 'BASE64'
      stage: 'CURRENT'
  delegate_to: localhost
