---
- name: Remove conflicting firewalld
  yum:
    name:
      - firewalld
      - firewalld-filesystem
    state: absent

- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: update

- name: Reboot to apply updates
  reboot:
  when: update.changed
